# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#

User.delete_all
Location.delete_all
University.delete_all
Friendship.delete_all
Event.delete_all

Location.create(id: '1', city: 'Chicago', state: 'IL', description: "The City of Chicago covers an  area of 60,000 hectares and sits 176 meters (578 feet) above sea level on the southwestern shore of Lake Michigan. At 190 km wide and 495 km long, its the 5th largest body of fresh water in the world. The city is traversed by the Chicago and Calumet rivers. Chicago's extensive parklands, including 3,000 hectares of city parks attract an estimated 86 million visitors annually. \nAs a multicultural city that thrives on the harmony and diversity of its neighborhoods, Chicago today embodies the values of America's heartland-integrity, hard work and community and reflects the ideals in the social fabric of  its 77 distinct neighborhoods. \nChicago is recognized across the United States as a very passionate sports town. Chicago is a leader in reforming public schools, enhancing public safety and security initiatives, providing affordable housing in attractive and economically sound communities, ensuring accessibility for all and fostering, social, economic and environmental sustainability.")
Location.create(id: '2', city: 'New York City', state: 'NY', description: "New York – often called New York City or the City of New York to distinguish it from the State of New York, of which it is a part – is the most populous city in the United States and the center of the New York metropolitan area, the premier gateway for legal immigration to the United States and one of the most populous urban agglomerations in the world. A global power city, New York exerts a significant impact upon commerce, finance, media, art, fashion, research, technology, education, and entertainment. Home to the headquarters of the United Nations, New York is an important center for international diplomacy[14] and has been described as the cultural and financial capital of the world.")
Location.create(id: '3', city: 'San Francisco', state: 'CA', description: "San Francisco (/sæn frənˈsɪskoʊ/), officially the City and County of San Francisco, is the cultural, commercial, and financial center of Northern California. The only consolidated city-county in California, San Francisco encompasses a land area of about 46.9 square miles (121 km2) on the northern end of the San Francisco Peninsula, giving it a density of about 18,187 people per square mile (7,022 people per km2). It is the most densely settled large city (population greater than 200,000) in the state of California and the second-most densely populated major city in the United States after New York City. San Francisco is the fourth-most populous city in California, after Los Angeles, San Diego and San Jose, and the 14th-most populous city in the United States—with a Census-estimated 2014 population of 852,469. The city and its surrounding areas are known as the San Francisco Bay Area, which is a part of the larger OMB designated San Jose-San Francisco-Oakland combined statistical area, the fifth most populous in the nation with an estimated population of 8.6 million.")
Location.create(id: '4', city: 'Washington, DC', state: 'DC', description: "Washington, D.C., formally the District of Columbia and commonly referred to as Washington, 'the District', or simply D.C., is the capital of the United States. The signing of the Residence Act on July 16, 1790, approved the creation of a capital district located along the Potomac River on the country's East Coast. The U.S. Constitution provided for a federal district under the exclusive jurisdiction of the Congress and the District is therefore not a part of any U.S. state.")
Location.create(id: '5', city: 'Las Vegas', state: 'NV', description: "Las Vegas, /lɑːs ˈveɪɡəs/ (locally, also pronounced as /lɑːs ˈvɛɡɨs/) officially the City of Las Vegas and often known as simply Vegas, is a city in the United States, the most populous city in the state of Nevada, the county seat of Clark County, and the city proper of the Las Vegas Valley. Las Vegas is an internationally renowned major resort city known primarily for gambling, shopping, fine dining and nightlife and is the leading financial and cultural center for Southern Nevada. The city bills itself as The Entertainment Capital of the World, and is famous for its mega casino–hotels and associated entertainment. A growing retirement and family city, Las Vegas is the 30th-most populous city in the United States, with a population of 603,488 at the 2013 United States Census Estimates.")
Location.create(id: '6', city: 'Austin', state: 'TX', description:"Austin is the capital of the US state of Texas and the seat of Travis County. Located in Central Texas, Austin is the 11th-most populous city in the United States and the fourth-most populous city in Texas. It was the third-fastest-growing large city in the nation from 2000 to 2006. Austin is also the second largest state capital in the United States, after Phoenix, Arizona. Austin had a July 1, 2013 population of 885,400 (U.S. Census Bureau estimate). The city is the cultural and economic center of the Austin–Round Rock metropolitan area, which had an estimated population of 1,883,051 as of July 1, 2013." )
Location.create(id: '7', city: 'Dallas', state: 'TX', description: "Dallas (/ˈdæləs/) is a major city in Texas and is the largest urban center of the fourth most populous metropolitan area in the United States. The city proper ranks ninth in the U.S. and third in Texas after Houston and San Antonio. The city's prominence arose from its historical importance as a center for the oil and cotton industries, and its position along numerous railroad lines. The bulk of the city is in Dallas County, of which it is the county seat; however, sections of the city are located in Collin, Denton, Kaufman, Tarrant and Rockwall counties. According to the 2010 United States Census, the city had a population of 1,197,816. The United States Census Bureau's estimate for the city's population increased to 1,257,676, as of 2013.")
Location.create(id: '8', city: 'Los Angeles', state: 'CA', description: "Los Angeles (lɒs ˈændʒəlɨs), officially the City of Los Angeles, often known by its initials L.A., is the second-largest city in the United States, and the most populous city in the U.S. state of California. Situated in Southern California, Los Angeles is known for its mediterranean climate, ethnic diversity, sprawling metropolis, and as the cultural center of the American entertainment industry. Los Angeles lies in a large coastal basin surrounded on three sides by mountains reaching up to and over 10,000 feet (3,000 m).")
Location.create(id: '9', city: 'Boston', state: 'MA', description: "Boston is the capital and largest city of the Commonwealth of Massachusetts in the United States. Boston also serves as county seat of Suffolk County. The city proper covers 48 square miles (124 km2) with an estimated population of 645,966 in 2014, making it the largest city in New England and the 24th largest city in the United States. The city is the anchor of a substantially larger metropolitan area called Greater Boston, home to 4.5 million people and the tenth-largest metropolitan area in the country. Greater Boston as a commuting region is home to 7.6 million people, making it the sixth-largest Combined Statistical Area in the United States.")
Location.create(id: '10', city: 'New Orleans', state: 'LA', description: "New Orleans is a major United States port and the largest city and metropolitan area in the state of Louisiana. The population of the city was 343,829 as of the 2010 U.S. Census. The New Orleans metropolitan area (New Orleans–Metairie–Kenner Metropolitan Statistical Area) had a population of 1,167,764 in 2010 and was the 46th largest in the United States. The New Orleans–Metairie–Bogalusa Combined Statistical Area, a larger trading area, had a 2010 population of 1,452,502.")
Location.create(id: '11', city: 'Princeton', state: 'NJ', description: "Princeton is a municipality with a borough form of government in Mercer County, New Jersey, United States, that was established in its current form on January 1, 2013, through the consolidation of the Borough of Princeton and Princeton Township. As of the 2010 United States Census, the municipality's population was 28,572, reflecting the former township's population of 16,265, along with the 12,307 in the former borough.")
Location.create(id: '12', city: 'New Haven', state: 'CT', description:"New Haven is the principal municipality in Greater New Haven, which had a total population of 862,477 in 2010. It is located on New Haven Harbor on the northern shore of the Long Island Sound in New Haven County, which in turn comprises the outer limits of the New York metropolitan area. It is the second-largest city in Connecticut (after Bridgeport), with a population of 129,779 people as of the 2010 United States Census. According to a census done by the Census Bureau as of July 1, 2012, the city had a population of 130,741.\nNew Haven was founded in 1638 by English Puritans, and a year later eight streets were laid out in a four-by-four grid, creating what is now commonly known as the 'Nine Square Plan', now recognized by the American Institute of Certified Planners as a National Planning Landmark. The central common block is New Haven Green, a 16-acre (6 ha) square, now a National Historic Landmark and the center of Downtown New Haven.\nNew Haven is the home of Yale University. The university is an integral part of the city's economy, being New Haven's biggest taxpayer and employer. Health care (hospitals and biotechnology), professional services (legal, architectural, marketing, and engineering), financial services, and retail trade also help to form an economic base for the city.")
Location.create(id: '13', city: 'Berkeley', state: 'CA', description: "Berkeley is a city on the east shore of San Francisco Bay in northern Alameda County, California. It is named after the eighteenth-century bishop and philosopher George Berkeley. It borders the cities of Oakland and Emeryville to the south and the city of Albany and unincorporated community of Kensington to the north. Its eastern border with Contra Costa County generally follows the ridge of the Berkeley Hills. Its population at the 2010 census was 112,580. It is one of the most politically liberal cities in the United States.\nBerkeley is the site of the oldest campus in the University of California system – the University of California, Berkeley – and of the Lawrence Berkeley National Laboratory that the university manages and operates. It is also home to the Graduate Theological Union.")

University.create(id: '1', name: 'University of Chicago', location_id: 1, description: "The University of Chicago (U of C, UChicago, or simply Chicago) is a private research university in Chicago, Illinois. The university consists of the College of the University of Chicago, various graduate programs and interdisciplinary committees organized into four divisions, six professional schools, and a school of continuing education. A highly regarded university internationally, beyond traditional academia, Chicago is also well known for its professional schools, which include the Pritzker School of Medicine, the Booth School of Business, the Law School, and the Divinity School. The university enrolls approximately 5,000 students in the College and about 15,000 students overall.", logo_url: 'http://upload.wikimedia.org/wikipedia/en/9/93/University_of_Chicago_logo.svg')
University.create(id: '2', name: 'Northwestern University', location_id: 1, description: "Northwestern University (NU) is a private research university with campuses in Evanston and Chicago in Illinois, United States, as well as Doha, Qatar. Composed of twelve schools and colleges, Northwestern offers 124 undergraduate degrees and 145 graduate and professional degrees.", logo_url: 'http://www.northwestern.edu/univ-relations/files/NU_Logo_purple.bmp')
University.create(id: '3', name: 'Harvard University', location_id: 9, description: "Harvard University is a private Ivy League research university in Cambridge, Massachusetts, established in 1636. Its history, influence and wealth have made it one of the most prestigious universities in the world.", logo_url: 'http://logonoid.com/images/harvard-logo.png')
University.create(id: '4', name: 'Princeton University', location_id: 11, description: "Princeton University is a private Ivy League research university in Princeton, New Jersey. Founded in 1746 in Elizabeth as the College of New Jersey, Princeton was the fourth chartered institution of higher education in the American colonies and thus one of the nine Colonial Colleges established before the American Revolution. The institution moved to Newark in 1747, then to the current site nine years later, where it was renamed Princeton University in 1896.", logo_url: 'http://w3.pppl.gov/communications/identity/logos/Princeton%20University/princeton-university-logo1.jpg')
University.create(id: '5', name: 'Stanford University', location_id: 3, description: "Stanford University (officially Leland Stanford Junior University) is a private research university in Stanford, California, and one of the world's most prestigious institutions, with the top position in numerous surveys and measures in the United States. Stanford was founded in 1885 by Leland Stanford, former governor of and U.S. senator from California and leading railroad tycoon, and his wife, Jane Lathrop Stanford, in memory of their only child, Leland Stanford, Jr., who had died of typhoid fever at age 15 the previous year.", logo_url: 'http://etkinlab.stanford.edu/images/stanford-university-logo.png')
University.create(id: '6', name: 'Yale University', location_id: 12, description: "Yale University is a private Ivy League research university in New Haven, Connecticut. Founded in 1701 as the 'Collegiate School,' the university is the third-oldest institution of higher education in the United States. In 1718, the school was renamed 'Yale College' in recognition of a gift from Elihu Yale, a governor of the British East India Company. Established to train Congregationalist ministers in theology and sacred languages, by 1777 the school's curriculum began to incorporate humanities and sciences. During the 19th century Yale gradually incorporated graduate and professional instruction, awarding the first Ph.D. in the United States in 1861 and organizing as a university in 1887.", logo_url: 'http://www.ranklogos.com/wp-content/uploads/2012/06/yale_logo.jpg')
University.create(id: '7', name: 'Columbia University', location_id: 2, description: "Columbia University in the City of New York, or simply Columbia University, is a private Ivy League research university located in Morningside Heights, in Upper Manhattan, New York City. Columbia is the oldest institution of higher learning in New York state, the fifth oldest in the United States, and one of the country's nine Colonial Colleges founded before the American Revolution. It was founded in 1754 as King's College by royal charter of George II of Great Britain. After the American Revolutionary War, King's College briefly became a state entity, and was renamed Columbia College in 1784. The University now operates under a 1787 charter that places the institution under a private board of trustees, and in 1896 it was further renamed Columbia University. That same year, the university's campus was moved from Madison Avenue to its current location in Morningside Heights, where it occupies more than six city blocks, or 32 acres (13 ha)", logo_url: 'http://www.columbia.edu/cu/juami/officialblack2.jpg')
University.create(id: '8', name: 'University of California, Berkeley', location_id: 13, description: "The University of California, Berkeley (also referred to as Berkeley, UC Berkeley, California or simply Cal)[8] is a major public research university located in Berkeley, California. It is the flagship campus of the University of California system, one of three parts in the state's public higher education plan, which also includes the California State University system and the California Community Colleges System.", logo_url: 'http://lux.lblsci.wpengine.com/wp-content/uploads/sites/6/2014/07/logo_ucberkeley.png')

User.create(id: '1', name: 'Matthias Meier', email: 'meierm@uchicago.edu', password: '123polizei', university_id: 1, graduation_year: 2015, major: 'Computer Science', bio: 'I love web development.', location_id: '1', interested_in_hosting: 'yes', interested_in_hanging_out: 'yes')
User.create(id: '2', name: 'Will Boyer', email: 'wboyer@northwestern.edu', password: 'dajs32ids', university_id: 2, graduation_year: 2013, major: 'Mathematics', bio: 'I am a Maths Geek.', location_id: '4', interested_in_hosting: 'no', interested_in_hanging_out: 'yes')
User.create(id: '3', name: 'Ralph Lesser', email: 'lesser@berkeley.edu', password: 'hajs2das', university_id: 8, graduation_year: 2015, major: 'Classics', bio: 'Missing California', location_id: '2', interested_in_hosting: 'yes', interested_in_hanging_out: 'yes')
User.create(id: '4', name: 'Rick Andrews', email: 'andrews@harvard.edu', password: 'asda123sd', university_id: 3, graduation_year: 2014, major: 'Economics', bio: 'HARVARD IS STILL THE BEST', location_id: '9', interested_in_hosting: 'no', interested_in_hanging_out: 'yes')
User.create(id: '5', name: 'Jessica Sanchez', email: 'sanchez@stanford.edu', password: 'asg3ggg4g', university_id: 5, graduation_year: 2013, major: 'Electrical Engineering', bio: 'Up for going out in Vegas', location_id: '5', interested_in_hosting: 'yes', interested_in_hanging_out: 'yes')
User.create(id: '6', name: 'Monica Spiegel', email: 'spiegel@yale.edu', password: 'ahjasd233', university_id: 5, graduation_year: 2013, major: 'Biology', bio: 'Missing Yale people', location_id: '7', interested_in_hosting: 'no', interested_in_hanging_out: 'yes')
User.create(id: '7', name: 'Ryan Lecher', email: 'rl@columbia.edu', password: 'aha12433', university_id: 6, graduation_year: 2015, major: 'German', bio: 'Give me a shout if you are in LA', location_id: '6', interested_in_hosting: 'yes', interested_in_hanging_out: 'yes')
User.create(id: '8', name: 'Susie Mitchell', email: 'susiem@princeton.edu', password: 'aasdr433', university_id: 4, graduation_year: 2013, major: 'Computer Science', bio: 'I am a tiger forever in my heart!! And big rangers fan!', location_id: '2', interested_in_hosting: 'yes', interested_in_hanging_out: 'yes')

Friendship.create(id: '1', requester_id: 1, friend_id: 3)
Friendship.create(id: '2', requester_id: 1, friend_id: 2)
Friendship.create(id: '3', requester_id: 2, friend_id: 4)
Friendship.create(id: '4', requester_id: 3, friend_id: 5)
Friendship.create(id: '5', requester_id: 6, friend_id: 4)
Friendship.create(id: '6', requester_id: 3, friend_id: 7)
Friendship.create(id: '7', requester_id: 4, friend_id: 1)
Friendship.create(id: '8', requester_id: 3, friend_id: 2)
Friendship.create(id: '9', requester_id: 2, friend_id: 7)

Event.create(id: 1, name: 'Princeton Reunions', university_id: 4, location_id: 11, address: 'Main Campus', start_time: DateTime.new(2015,5,22,17), end_time: DateTime.new(2015,5,24,23), description: 'Reunions weekend attracts almost 25,000 alumni, family and friends for walks, talks, community service projects, Alumni-Faculty Forums, picnics, parties, concerts, dancing, meeting old friends, making new ones and, of course, marching in the One and Only P-rade! - See more at: http://alumni.princeton.edu/goinback/reunions/#sthash.JLm4qbYE.dpuf', organizer_contact_email: 'susie@princeton.edu')
Event.create(id: 2, name: 'UChicago Alumni Meetup', university_id: 1, location_id: 9, address: 'Scholars Inn, West Washington Street 44',  start_time: DateTime.new(2015,5,29,18), end_time: DateTime.new(2015,5,29,22), description: 'Dear Boston Alumni, we are happy to have an informal UChicago Alumni Meetup this May. We will meet at the Scholars Inn, as always! Looking forward!', organizer_contact_email: 'meierm@uchicago.edu')
Event.create(id: 3, name: 'Stanford Alumni Social', university_id: 5, location_id: 5, address: 'LV Brew House, McKinsey Ave 44', start_time: DateTime.new(2015,6,1,19), end_time: DateTime.new(2015,6,1,23), description: 'Monthly Alumni social at the Las Vegas Brew House. Friends and family are welcome to join!', organizer_contact_email: 'sanchez@stanford.edu')
Event.create(id: 4, name: 'Bulldogs in Dallas - Monthly Stammtisch', university_id: 6, location_id: 7, address: 'Tiger Inn, Boston Avenue and 44th Street', start_time: DateTime.new(2015,6,10,17), end_time: DateTime.new(2015,6,10,22), description: 'Join us for our monthly Stammtisch at the Tiger Inn!', organizer_contact_email: 'spiegel@yale.edu')
Event.create(id: 5, name: 'Annual Washington Harvard-Club Summer BBQ', university_id: 3, location_id: 4, address: 'tba', start_time: DateTime.new(2015,7,3,18), end_time: DateTime.new(2015,7,3,22), description: 'The annual summer BBQ is an established tradition of the Washington Harvard-Club and an event not to be missed. We will serve all sorts of meats, sausages and grilled veggies as well as a variety of soft drinks and cocktails. The location will be announced closer to the event!', organizer_contact_email: 'andrews@harvard.edu')
Event.create(id: 6, name: 'Columbia Alumni River Cruise', university_id: 7, location_id: 6, address: 'Details announced later!', start_time: DateTime.new(2015,7,22,16), end_time: DateTime.new(2015,7,22,19), description: 'Join us for an awesome river cruise. More details to be announced soon, but save the date!', organizer_contact_email: 'rl@columbia.edu')
Event.create(id: 7, name: 'Berkeley New York After-Work Meetup', university_id: 7, location_id: 2, address: 'The Professional Cocktail Bar, Rowley Street 44', start_time: DateTime.new(2015,7,1,19), end_time: DateTime.new(2015,7,1,22), description: 'Come along to our monthly after-work meetup. This is a great way to stay in touch with old Berkeley friends and meet alumni in the city.', organizer_contact_email: 'lesser@berkeley.edu')

puts "Seeded succesfully."
